keywords = [
  '.NET Framework',
  '2-3 Tree',
  '2-3-4 Tree',
  '3D Printer',
  '3D Printing',
  'Aborted Transaction',
  'Absolute Code',
  'Absolute Path Name',
  'Abstract',
  'Abstract Base Class',
  'Abstract Class',
  'Abstract Data Type',
  'Abstract Factory Pattern',
  'Abstract Method',
  'Abstract Syntax Tree',
  'Abstract Window Toolkit',
  'Abstraction',
  'Access',
  'Access Control',
  'Access Control List',
  'Access Delay',
  'Access Latency',
  'Access List',
  'Access Matrix',
  'Access Modifier',
  'Access Network',
  'Access Path',
  'Access Point',
  'Access Router',
  'Accounting Management',
  'Accreditation',
  'Acknowledgement Number',
  'Acknowledgment',
  'ActionScript',
  'Activation Function',
  'Active Directory',
  'Active Optical Network',
  'Active Queue Management Algorithms',
  'Active Server Pages',
  'ActiveX Control',
  'Activity Diagram',
  'Actual Argument',
  'Acyclic Graph',
  'Ad Hoc Network',
  'Ada',
  'Adapter',
  'Adapter Pattern',
  'Adaptive Congestion Control',
  'Adaptive Mutex',
  'Adaptive Streaming',
  'Additional-Reference-Bits Algorithm',
  'Address',
  'Address Aggregation',
  'Address Bar',
  'Address Binding',
  'Address Indirection',
  'Address Resolution Protocol',
  'Address-space Identifiers',
  'Adjacency Matrix',
  'Administrative Complexity',
  'Administrator',
  'Admission Control Algorithm',
  'Adobe Flash Player',
  'Advanced Audio Coding',
  'Advanced Encryption Standard',
  'Advanced Micro Devices',
  'Advanced Research Projects Agency',
  'Advanced Technology Attachment',
  'Affine Transformation',
  'Agent Advertisement',
  'Agent Discovery',
  'Agent Solicitation',
  'Agglomerative Clustering',
  'Aggregate Function',
  'Aggregation',
  'Agile',
  'Aging Time',
  'Aho-Corasick',
  'Ajax',
  'Alan Turing',
  'Alexa',
  'Algorithm',
  'Algorithmic Complexity',
  'Alias',
  'All-Pairs Shortest Paths',
  'Allocator',
  'Alpha Go',
  'Alter Table',
  'Alternating Bit Protocol',
  'Amazon Cloud',
  'Amazon Web Services',
  'American National Standards Institute',
  'American Standard Code for Information Interchange',
  'Analog Audio',
  'Analog Signal',
  'Analysis Pass',
  'Analytic Combinatorics',
  'Analytical Workspace',
  'Ancestor',
  'Anchor',
  'Android',
  'Android Developer Tools',
  'Android Emulator',
  'Android Wear',
  'AngularJS',
  'Anjuta',
  'Anomaly Detection',
  'Anonymity',
  'Anonymous',
  'Anonymous Union',
  'Antenna',
  'Antivirus Software',
  'Anycast',
  'Apache',
  'Apache Subversion',
  'Apache Web server',
  'App Store',
  'Apple Watch',
  'Application',
  'Application Architecture',
  'Application Binary Interface',
  'Application Design',
  'Application Development Framework',
  'Application Gateway',
  'Application Layer',
  'Application Migration',
  'Application Programming Interface',
  'Application Server',
  'Apply Operator',
  'Apriori Rule',
  'Arbitrated Loop',
  'Arcade Game',
  'Architectural Patterns',
  'Architecture',
  'Arduino',
  'Argument',
  'Arithmetic Logic Unit',
  'Arithmetic Operator',
  'Arpanet',
  'Array',
  'Articulation Point',
  'Artificial Intelligence',
  'Assembler',
  'Assembly',
  'Assertions',
  'Assignment',
  'Assignment Edge',
  'Assignment Operation',
  'Associate Rule Learning',
  'Association',
  'Association Rule Learning',
  'Asymmetric Digital Subscriber Line',
  'Asymmetric Key Encryption',
  'Asymmetric Multiprocessing',
  'Asynchronous',
  'Asynchronous JavaScript and XML',
  'Asynchronous Procedure Call',
  'Asynchronous Thread Cancellation',
  'Asynchronous Transfer Mode',
  'ATI Technologies',
  'Atomic Transaction',
  'Atomic Value',
  'Attention',
  'Attribute',
  'Attribute Inheritance',
  'Augmentation Rule',
  'Augmented Reality',
  'Authentication',
  'Authentication Key',
  'Authorization',
  'Auto Declaration',
  'Autoclick',
  'Automata',
  'Automatic Job Sequencing',
  'Automatic Repeat reQuest protocols',
  'Automatic Storage Manager',
  'Automatic Type Conversion',
  'Automatic Workload Repository',
  'Automaton',
  'Automotive Engineering',
  'Autonomous System Number',
  'Available Bit Rate',
  'Avast',
  'Avatar',
  'Average Case Complexity',
  'Average Response Time',
  'Average Seek Time',
  'AVL Tree',
  'B-tree',
  'Backbone area',
  'Backdoor',
  'Background Process',
  'Backlink',
  'Backpropagation',
  'Backside Cache',
  'Backtracking',
  'Backup',
  'Bad Sector',
  'Bag of Features',
  'Bag of Words',
  'Balance Tree',
  'Balanced Binary Search Tree',
  'Balanced Range-Partitioning',
  'Balanced Tree',
  'Bandwidth',
  'Bandwidth Flooding',
  'Bandwidth Provisioning',
  "Banker's algorithm",
  'Banner',
  'Base Class',
  'Base Register',
  'Base Station',
  'Base Station Controller',
  'Base Station System',
  'Base Transceiver Station',
  'Bash',
  'Basic Data Type',
  'Basic Encoding Rules',
  'Basic Input/Output Stream',
  'Basic Service Set',
  'Batch',
  'Battery',
  "Bayes' theorem",
  'Bayesian Classifiers',
  'Bayesian Network',
  'Beacon Frame',
  'Behavior',
  'Behavioral Pattern',
  'Benchmark',
  'Berkeley Internet Name Domain',
  'Berkeley Packet Filter',
  'Best Case Complexity',
  'Best-effort Delivery Service',
  'Bi-connected Component',
  'Biased Protocol',
  'Bidirectional',
  'Bidirectional Data Transfer',
  'Bidirectional Iterators',
  'Big Data',
  'Big O',
  'Big-bang Approach',
  'Big-endian',
  'Bigtable',
  'Binary',
  'Binary Code',
  'Binary Digit',
  'Binary Exponential Backoff Algorithm',
  'Binary File',
  'Binary Insertion Sort',
  'Binary Number',
  'Binary Recursion',
  'Binary Search',
  'Binary Search Tree',
  'Binary Semaphore',
  'Binary Split',
  'Binary Tree',
  'Bing',
  'Binomial Tree',
  'Bioinformatics',
  'Biometrics',
  'Bipartite Graph',
  'Bipartite Matching',
  'Bit',
  'Bit Error Rate',
  'Bit Mask',
  'Bit per Second',
  'Bit-interleaved Parity Organization',
  'Bit-level Striping',
  'Bitcoin',
  'BitDefender',
  'Bitmap',
  'BitTorrent',
  'Bitwise Copy',
  'Bitwise Operator',
  'Black-box Transformations',
  'BlackBerry World',
  'Blank',
  'Blind Writes',
  'Blob Detection',
  'Block',
  'Block Cipher',
  'Block Nested-loop Join',
  'Block-interleaved Distributed Parity',
  'Block-interleaved Parity Organization',
  'Block-level Striping',
  'Blockchain',
  'Blu-ray',
  'Blue Screen of Death',
  'Bluetooth',
  'Bluetooth Low Energy',
  'Bookmark',
  'Boolean',
  'Boolean Operation',
  'Boosting',
  'Boot Control Block',
  'Boot Disk',
  'Boot Partition',
  'Boot Sector',
  'Bootloader',
  'Bootstrap',
  'Bootstrap Program',
  'Bootstrapping',
  'Border Gateway Protocol',
  'Boruvka Algorithm',
  'Botnet',
  'Bottleneck',
  'Bottleneck Link',
  'Bottom-up Programming',
  'Boyce-Codd Normal Form',
  'Branch Statement',
  'Breadth First Search',
  'Bridge',
  'Bridge Pattern',
  'Broadband',
  'Broadcast',
  'Broadcast Data',
  'Broadcast Domain',
  'Broadcast Routing Algorithm',
  'Broadcast Storm',
  'Broadcasting',
  'Broken link',
  'Browser',
  'Brute Force',
  'Brute Force Search',
  'BTalk',
  'Bubble Sort',
  'Bucket Sort',
  'Buffer',
  'Buffer Cache',
  'Buffer Manager',
  'Buffer Overflow',
  'Buffer Pool',
  'Buffered Distributor',
  'Buffering',
  'Bug',
  'Builder Pattern',
  'Builtin Class',
  'Builtin Data Type',
  'Bulk Export/Import/Search',
  'Bully Algorithm',
  'Burst Size',
  'Bus Architecture',
  'Bus System',
  'Business Intelligent',
  'Business Logic Layer',
  'Bytecode',
  'C',
  'C Plus Plus',
  'C Sharp',
  'C-style casting',
  'Cable',
  'Cable Internet Access',
  'Cable Modem Termination System',
  'Cache',
  'Cache Coherence Problem',
  'Cache Coherency',
  'Caesar Cipher',
  'Calculator',
  'Calculus',
  'Call Admission',
  'Call Level Interface',
  'Call Setup Protocol',
  'Callable Statement',
  'Callback',
  'Candidate Key',
  'Canonical Cover',
  'Canonical Hostname',
  'Capital Letter',
  'Caps Lock',
  'Captcha',
  'Card',
  'Carrier Sense Multiple Access',
  'Cartesian Product',
  'Cascadeless Schedule',
  'Cascading Style Sheet',
  'Cascading Termination',
  'Case Construct',
  'Case Sensitivity',
  'Case Study',
  'Casting',
  'Casting Data Type',
  'Casting Operator',
  'Catalog',
  'Catch',
  'Catching Exception',
  'Categories',
  'Cellphone',
  'Cellular Network',
  'Central Processing Unit',
  'Centralized Architecture',
  'Centralized Deadlock Detection',
  'Centroid',
  'Centroid Decomposition',
  'Certificate',
  'Certificate Authority',
  'Chain of Responsibility Pattern',
  'Challenge-response Authentication',
  'Change Isolation Level',
  'Channel',
  'Channel Propagation Delay',
  'Character',
  'Character Encoding',
  'Character Map',
  'Chatbot',
  'Checkpoint Log Record',
  'Checksum',
  'Child Process',
  'Chinese Remainder Theorem',
  'Chipset',
  'Chromebook',
  'Cipher-block Chaining',
  'Ciphertext',
  'Circuit Switching',
  'Circular Linked List',
  'Circular Scheduling',
  'Cisco Systems',
  'Class',
  'Class Declaration',
  'Class Diagram',
  'Class Implementation',
  'Class Name',
  'Class-level Member',
  'Class-level Method',
  'Classification',
  'Classification Hierarchy',
  'Classless Inter-Domain Routing',
  'Click',
  'Client',
  'Client Application Buffer',
  'Client Socket',
  'Client-server Application',
  'Client-server Model',
  'Client-server Paradigm',
  'Client-server System',
  'Client-side Scripting',
  'Clock Rate',
  'Clock Speed',
  'Clone',
  'Cloning Pattern',
  'Cloud Computing',
  'Cloud Storage',
  'Cluster',
  'Cluster Index',
  'Cluster Remapping',
  'Cluster Selection Strategy',
  'Coaxial Cable',
  'COBOL',
  'Cocktail Sort',
  'Code',
  'Code Block',
  'Code Breaking',
  'Code Division Multiple Access',
  'Code Duplication',
  'Code Generation',
  'Code Reuse',
  'Codec',
  'Coding Theory',
  'Coefficient',
  'ColdFusion Markup Language',
  'Collect Function',
  'Collision',
  'Collision Detection',
  'Collision Domain',
  'Column-oriented Storage',
  'Combinatorics',
  'Combo Box',
  'Command Pattern',
  'Command-line Interface',
  'Comment',
  'Commit',
  'Commit Protocol',
  'Common Gateway Interface',
  'Common Internet File System',
  'Common Language Runtime',
  'Common Subexpression Elimination',
  'Communication',
  'Communication Diagram',
  'Communication Session',
  'Communication System Calls',
  'Compact Disc',
  'Compact Disk',
  'Compatibility Function',
  'Compensation Log Records',
  'Compile',
  'Compile Error',
  'Compiler',
  'Complex Data Type',
  'Complex Instruction Set Computing',
  'Complexity',
  'Component',
  'Component Object Model',
  'Composite Number',
  'Composite Pattern',
  'Composite Structure Diagram',
  'Composition',
  'Compound Key',
  'Compound Statement',
  'Compression Ratio',
  'Compression Unit',
  'Computation Migration',
  'Computational Complexity Theory',
  'Computational Geometry',
  'Computer Bus',
  'Computer Environment',
  'Computer Graphics',
  'Computer Network',
  'Computer Science',
  'Computer Vision',
  'Computer-aided Design',
  'Concatenation',
  'Conceptual Design',
  'Concrete Class',
  'Concrete Subclass',
  'Concurrency Control',
  'Concurrency Pattern',
  'Concurrency-control Algorithm',
  'Condition',
  'Condition-defined Entity Set',
  'Conditional Expression',
  'Confidentiality',
  'Configuration Management',
  'Conflict Resolution Module',
  'Conformance Level',
  'Congestion Avoidance',
  'Congestion Control',
  'Congestion Indication Bit',
  'Connected Component',
  'Connection-establishment Request',
  'Connection-oriented Service',
  'Connection-oriented Socket',
  'Connectionless Socket',
  'Connectivity',
  'Consistency',
  'Consistency Checking',
  'Console',
  'Const Casting',
  'Const Member Functions',
  'Constant',
  'Constant Bit Rate',
  'Constant Time Complexity',
  'Constraint',
  'Constraint Programming',
  'Constructor',
  'Consumer Electronics Show',
  'Consumers',
  'Container',
  'Content',
  'Content Delivery Network',
  'Content Distribution Network',
  'Content Management System',
  'Content Provider Network',
  'Context Menu',
  'Context Switch',
  'Contiguous Memory Allocation',
  'Continuous Delivery',
  'Continuous Integration',
  'Control Abstraction',
  'Control Flow',
  'Control Plane Software',
  'Control Register',
  'Control Structure',
  'Control Unit',
  'Control-card Interpreter',
  'Controlled Flooding',
  'Controller',
  'Converge',
  'Conversation Group',
  'Conversational Application',
  'Converter',
  'Converting Data Types',
  'Convex Hull',
  'Convolution',
  'Cookie',
  'Cooling Fan',
  'Cooperating Process',
  'Coordinates',
  'Copy',
  'Copy Constructor',
  'Core Dump',
  'Correlated Subqueries',
  'Correlation Variables',
  'Cortana',
  'Cost function',
  'Counting Sort',
  'Counting-based Page Replacement',
  'Coursera',
  'Crash Dump',
  'Create Assertion',
  'Create Distinct Type',
  'Creational pattern',
  'Critical Node',
  'Critical-section Problem',
  'Cross Compiler',
  'Cross Platform',
  'Cross Product',
  'Cross-platform Software',
  'Cross-site Request Forgery',
  'Cross-site Scripting',
  'Crossbar Switch',
  'Crowdfunding',
  'Crowdsourcing',
  'Cryptanalysis',
  'Cryptocurrency',
  'Cryptographic Hash Function',
  'Cryptography',
  'Cryptojacking',
  'Cryptology',
  'Cumulative Acknowledgment',
  'Cursor',
  'Customer-provider Relationship',
  'Cut Vertex',
  'Cybercrime',
  'Cycle',
  'Cycle Stealing',
  'Cyclic Redundancy Check',
  'Cygwin',
  'Cylinder',
  'Cylinder Group',
  'Daemon',
  'Dalvik Virtual Machine',
  'Dashboard',
  'Data',
  'Data Abstraction',
  'Data Access Layer',
  'Data Capability',
  'Data Center',
  'Data Center Network',
  'Data Cleansing',
  'Data Control Language',
  'Data Definition Language',
  'Data Encryption Algorithm',
  'Data Encryption Standard',
  'Data Flow Diagram',
  'Data Hiding',
  'Data Link',
  'Data Link Layer',
  'Data Loss',
  'Data Management',
  'Data Manipulation Language',
  'Data Member',
  'Data Migration',
  'Data Mining',
  'Data Models',
  'Data Parallelism',
  'Data Query Language',
  'Data Server System',
  'Data Storage and Definition Language',
  'Data Structure',
  'Data Structure Diagram',
  'Data Transfer',
  'Data Transfer Object',
  'Data Transfer Rate',
  'Data Type',
  'Data Type Definition',
  'Data Warehouse',
  'Database',
  'Database Administrator',
  'Database Designer',
  'Database Graph',
  'Database Instance',
  'Database Management System',
  'Database Programmer',
  'Database Resource Management',
  'Database Schema',
  'Database System',
  'Database Task Group',
  'Database Writer Process',
  'Datacenter',
  'Datagram',
  'Datagram Network',
  'DataGrid Control',
  'Datalink Layer',
  'Datalog',
  'Dataset',
  'Datetime',
  'Deadline',
  'Deadlock',
  'Deadlock-detection Coordinator',
  'Debian',
  'Debug',
  'Debugger',
  'Debugging',
  'Decentralized Routing Algorithm',
  'Decision Problem',
  'Decision Table',
  'Decision Tree',
  'Decision-support System',
  'Decision-tree classifiers',
  'Declaration',
  'Declarative Region',
  'Declare',
  'Decode',
  'Decomposition',
  'Decomposition Rule',
  'Decorator Pattern',
  'Decrement Operator',
  'Decryption',
  'Deduplication',
  'Deep Belief Network',
  'Deep Blue',
  'Deep Copy',
  'Deep Learning',
  'Deep Packet Inspection',
  'Deep Web Crawler',
  'DeepBlue',
  'Default Argument',
  'Default Constructor',
  'Default Gateway',
  'Default Name Server',
  'Default Router',
  'Default Signal Handler',
  'Default Value',
  'Deferred Integrity Constraint',
  'Define',
  'Definition',
  'Degree',
  'Degree-two Consistency',
  'Delay-sensitive',
  'Delay-write Policy',
  'Delegation',
  'Delete',
  'Delimiter',
  'Delta Relation',
  'Demand Paging',
  'Demand-driven Pipelining',
  'Demultiplexing',
  'Denial of Service',
  'Denormalization',
  'Dense Graph',
  'Dependency Preservation',
  'Deployment Diagram',
  'Depth Camera',
  'Depth First Search',
  'Depth Map',
  'Dequeue',
  'Dereferencing Operator',
  'Derived Class',
  'Descriptive Attribute',
  'Descriptive Pattern',
  'Design Pattern',
  'Destination Port Number',
  'Destination Route',
  'Destination Vertex',
  'Destructor',
  'Deterministic Finite Automaton',
  'Deterministic Modeling',
  'Developer',
  'Device Firmware Upgrade',
  'Device-management System Call',
  'Dial-up',
  'Diameter of Tree',
  'Dictionaries',
  'Dictionary Attack',
  'Diffie-Hellman Algorithm',
  'Digital Certificate',
  'Digital Coin',
  'Digital Signal',
  'Digital Signal Processing',
  'Digital Signature',
  'Digital Signature Algorithm',
  'Digital Subscriber Line',
  'Digital Twin',
  'Digital Video Camera',
  'Digital Watermarking',
  'Dijkstra Algorithm',
  'Dimension',
  'Dimensioning Best-effort Network',
  'Dining Philosophers Problem',
  'Direct Access',
  'Direct Memory Access',
  'Direct Routing',
  'Direct Sequence Wideband',
  'Direct-access Storage',
  'Directed Acyclic Graph',
  'Directory',
  'Directory Information Tree',
  'Directory Service',
  'Directory System',
  'DirectX',
  'Dirty Bit',
  'Dirty Block',
  'Dirty Page Table',
  'Dirty Read',
  'Dirty Write',
  'Disable Trigger',
  'Disconnected Operation',
  'Discrete Fourier Transform',
  'Discrete Mathematics',
  'Discriminative',
  'Disjoint Entity Set',
  'Disjoint Set Union',
  'Disjoint Specialization',
  'Disjoint-set Data Structure',
  'Disjunction',
  'Disk Controller',
  'Disk Striping',
  'Disk-arm-scheduling',
  'Disk-based Operating System',
  'Dispatch',
  'Dispatch Latency',
  'Displacement Vector',
  'Distance Vector Algorithm',
  'Distinct',
  'Distinct Type',
  'Distinguished Name',
  'Distributed Application',
  'Distributed Database',
  'Distributed Denial-of-Service',
  'Distributed File System',
  'Distributed Hash Table',
  'Distributed Interframe Space',
  'Distributed System',
  'Distributed-lock Manager',
  'Distribution',
  'Divide and Conquer',
  'Django',
  'Docker',
  'Document Object Model',
  'Document Type Definition',
  'Domain',
  'Domain Constraint',
  'Domain Key Normal Form',
  'Domain Name',
  'Domain Name System',
  'Domain Relational Calculus',
  'Donald Knuth',
  'Doodles',
  'Dot Net',
  'Dotted-decimal Notation',
  'Double Data Rate',
  'Double Hashing',
  'Double-ended Priority Queue',
  'Double-ended Queue',
  'Double-pipelined Hash-join',
  'Doubly Linked List',
  'Downcasting',
  'Download',
  'Dreamweaver',
  'Drill Down',
  'Drive Bay',
  'Driver-Manager class',
  'Drop Trigger',
  'Dropbox',
  'Dual-booted System',
  'Dual-stack Approach',
  'Dumping',
  'Duplicate Elimination',
  'Durability',
  'Dynamic Allocation of Memory',
  'Dynamic Array',
  'Dynamic Casting',
  'Dynamic Host Configuration Protocol',
  'Dynamic Link Library',
  'Dynamic Memory',
  'Dynamic Programming',
  'Dynamic Routing Algorithm',
  'Dynamic SQL',
  'Dynamic Storage Allocation Problem',
  'Dynamic Storage Duration',
  'E-book',
  'E-commerce',
  'E-learning',
  'Early Binding',
  'Eclipse',
  'Edge',
  'Edge Computing',
  'Edge Router',
  'Effective Bandwidth',
  'Effective Variable',
  'Efficiency',
  'Eigenvalue',
  'Eigenvector',
  'Eight Queens Puzzle',
  'Elastic Application',
  'Elastic Compute Cloud',
  'Election Algorithm',
  'Electromagnetic Noise',
  'Electronic Disk',
  'Electronic Mail',
  'Element',
  'Elevator Algorithm',
  'Elimination Rules for Routes',
  'Emacs',
  'Email',
  'Embedded SQL',
  'Embedded System',
  'Embedding',
  'EmguCV',
  'Emoji',
  'Empty Relation',
  'Emulator',
  'Encapsulation',
  'Encapsulation Security Payload',
  'Encrypted Media Extensions',
  'Encryption',
  'End of File',
  'End System',
  'End User',
  'End-point Authentication',
  'End-to-end Congestion Control',
  'End-to-end Delay',
  'End-to-end Principle',
  'End-to-end Throughput',
  'End-user Information',
  'Endianness',
  'Enigma',
  'Enqueue',
  'Enterprise',
  'Enterprise Information',
  'Enterprise Resource Planning',
  'Enterprises and Access Networks',
  'Entity',
  'Entity Data Model',
  'Entity Relationship Diagram',
  'Entity Set',
  'Entity-relationship Diagram',
  'Entity-relationship Model',
  'Entropy',
  'Entry Page',
  'Enumeration',
  'Equi-joins',
  'Ergonomics',
  'Eric Schmidt',
  'Error Checking',
  'Error Concealment',
  'Error Correcting Code',
  'Error Detection',
  'Estimate',
  'Ethernet',
  'Euclidean Algorithm',
  'Euclidean Distance',
  'Euler Diagram',
  "Euler's Formula",
  'Evaluation Primitive',
  'Event Latency',
  'Event-driven Programming',
  'Evolved Packet Core',
  'Excel',
  'Except Clause',
  'Exception',
  'Exception Handler',
  'Exception Specification',
  'Exchange System',
  'Exclamation Point',
  'Exclusive Lock',
  'Exclusive-mode Lock',
  'Executable and Linkable Format',
  'Executable File',
  'Exhaustive Search',
  'Existence Bitmap',
  'Exists Clause',
  'Expedited Forwarding',
  'Expert System',
  'Explicit Casting',
  'Explicit Congestion Notification',
  'Explicit Forward Congestion Indication Bit',
  'Explicit Instantiation',
  'Explicit Rate',
  'Explicit Rate Field',
  'Explicit Specialization',
  'Exploding Gradient',
  'Exponent',
  'Exponential Average',
  'Exponential Time',
  'Exponential Weighted Moving Average',
  'Extended Euclidean Algorithm',
  'Extended Finite State Machine',
  'Extended Reality',
  'Extensibility Contract',
  'eXtensible Application Markup Language',
  'Extensible Authentication Protocol',
  'Extensible HyperText Markup Language',
  'Extensible Markup Language',
  'Extensible Stylesheet Language Transformations',
  'External Fragmentation',
  'External Language Routine',
  'External Linkage',
  'External Sort-merge Algorithm',
  'External Storage',
  'Extract',
  'Extraction',
  'Extraction Operator',
  'Extreme Programming',
  'Eye tracking',
  'F Sharp',
  'Facade Pattern',
  'Face Detection',
  'Facebook',
  'Fact Tables',
  'Factorial',
  'Factorization',
  'Factory Method',
  'Factory Method Pattern',
  'Fail-stop Assumption',
  'False Cycle',
  'Fatal Error',
  'Fault Management',
  'Fax Machine',
  'Feature Matching',
  'Fedora',
  'Fiber Distributed Data Interface',
  'Fiber-Optic Cable',
  'Fibonacci',
  'Fibonacci Heap',
  'Fibonacci Number',
  'Fibonacci Sequence',
  'Fibre Channel interface',
  'File',
  'File Allocation Table',
  'File Extension',
  'File Header',
  'File Manager',
  'File Organization',
  'File Pointer',
  'File Scan',
  'File Sharing',
  'File System',
  'File Transfer Protocol',
  'Fine-granularity Parallelism',
  'Fingerprint',
  'Finite State Machine',
  'Firebase',
  'Firewall',
  'FireWire',
  'First Come First Serve',
  'First Committer Wins',
  'First In Last Out',
  'First Updater Wins',
  'First-come-first-served scheduling',
  'Fixed-length Label',
  'Flag Field',
  'Flash Sort',
  'Flash Storage',
  'Flash Translation Layer',
  'Floating Point',
  'FLoating Point Operations Per Second',
  'Floppy Disk',
  'Flow Chart',
  'Flow Control',
  'Floyd Algorithm',
  'Flushing',
  'Flushing Buffer',
  'Flyweight Pattern',
  'Folder',
  'Font',
  'Font Size',
  'Font Word',
  'Force Policy',
  'Forced Output',
  'Ford-Bellman Algorithm',
  'Foreground Process',
  'Foreign Address',
  'Foreign Key',
  'Formal Language',
  'Formal Parameter',
  'Formal Variable',
  'Fortran',
  'Forward Error Correction',
  'Forwarding Function',
  'Forwarding Plane',
  'Forwarding Table',
  'Four Color Theorem',
  'Fourier Transform',
  'Foursquare',
  'Fractal',
  'Fragmentation',
  'Frame',
  'Framework',
  'Framework Application',
  'Free Space Control Record',
  'Frequency Division Multiplexing',
  'Friend',
  'Friend Class',
  'Friend Function',
  'Front-end',
  'Full Outer Join',
  'Full-duplex Service',
  'Full-table Block Cipher',
  'Fully Connected',
  'Fully Connected Topology',
  'Function',
  'Function Declaration',
  'Function Library',
  'Function Overloading',
  'Function Pointer',
  'Function Polymorphism',
  'Function Prototype Scope',
  'Function Template',
  'Function Wrapper',
  'Function-based Indices',
  'Functional Dependency',
  'Functional Overloading',
  'Functional Polymorphism',
  'Functional Programming',
  'Functional Requirements',
  'Functionally Determined Attributes',
  'Functors',
  'Fuzzy Checkpoint',
  'Fuzzy Logic',
  'Gadget',
  'Galaxy Fold',
  'Game Designer',
  'Game Theory',
  'Gamification',
  'Gang of Four',
  'Garbage Collection',
  'Garbage Collector',
  'Gateway',
  'Gateway Router',
  'Gaussian',
  'Gaussian Elimination',
  'General Public License',
  'Generalization',
  'Generalized Inverted Index',
  'Generalized Packet Radio Service',
  'Generalized Projection',
  'Generalized Search Tree',
  'Generating Function',
  'Generative',
  'Generative Adversarial Network',
  'Generative Pre-trained Transformer',
  'Generic Code',
  'Generic Programming',
  'Generic Type',
  'Genetic Algorithm',
  'Geographic Data',
  'Geographic Information System',
  'Ghost Site',
  'Gigabit Ethernet',
  'Gigabyte',
  'Gini measure',
  'GitHub',
  'Glassfish',
  'Glitches',
  'Global Class Identifier',
  'Global Company Identifier',
  'Global Descriptor Table',
  'Global Namespace',
  'Global Offset Table',
  'Global Positioning System',
  'Global Product Identifier',
  'Global Routing Algorithm',
  'Global System for Mobile',
  'Global Variable',
  'Global Wait-for Graph',
  'Golang',
  'Google API',
  'Google App Engine',
  'Google Apps',
  'Google Brain',
  'Google Cardboard',
  'Google Chrome',
  'Google Colab',
  'Google Doodle',
  'Google Drive',
  'Google Glass',
  'Google Hummingbird',
  'Google I/O',
  'Google Instant',
  'Google Maps',
  'Google Nexus',
  'Google Now',
  'Google Panda',
  'Google Penguin',
  'Google Play',
  'Google Street View',
  'Google Web Toolkit',
  'Gradient',
  'Gradient Descent',
  'Grant',
  'Graph',
  'Graph API',
  'Graph Coloring',
  'Graph-based Protocol',
  'Graphical User Interface',
  'Graphics',
  'Graphics Card',
  'Graphics Device Interface',
  'Graphics Interchange Format',
  'Graphics Processing Unit',
  'Greatest Common Divisor',
  'Greedy Algorithm',
  'Grid Computing',
  'Group By',
  'Group Identifiers',
  'Hackathon',
  'Hacker',
  'Hadoop',
  'Half Life',
  'Halting Problem',
  'Hamilton Cycle',
  'Hamming Distance',
  'Handoff',
  'Handshake',
  'Hard Coding',
  'Hard Disk Drive',
  'Hardware',
  'Hardware Acceleration',
  'Hardware Data Plane',
  'hardware-abstraction layer',
  'harmonic mean',
  'Hash',
  'Hash Cluster Access',
  'Hash Function',
  'Hash Join',
  'Hash Table',
  'Hash Tree',
  'Hashed Page Table',
  'Hashtag',
  'Haskell',
  'Haswell',
  'Head-of-the-line Blocking',
  'Header',
  'Header Checksum',
  'Header File',
  'Header Information',
  'Heap',
  'Heap File',
  'Heap Memory',
  'Heap Sort',
  'Heartbleed',
  'Heuristics',
  'Hibernate',
  'Hidden Layer',
  'Hidden Markov Model',
  'Hidden Terminal',
  'Hierarchical Architecture',
  'Hierarchical Classification',
  'Hierarchical Clustering',
  'Hierarchical Data Model',
  'Hierarchical Routing',
  'Hierarchical Storage Management',
  'Hierarchical Structure',
  'High Dynamic Range',
  'High Performance Computing',
  'High Speed Packet Access',
  'high-level data link control',
  'High-level Shader Language',
  'High-Performance Computer',
  'Higher Order Function',
  'Hill Climbing',
  'HipHop Virtual Machine',
  'Histogram',
  'Histogram Equalization',
  'Histogram Matching',
  'Histogram Specification',
  'Hologram',
  'Holography',
  'Hololens',
  'Home Location Register',
  'Honeycomb',
  'Horizontal Fragmentation',
  'Host',
  'Host Adapter',
  'Host Aliasing',
  'Host Identity Protocol',
  'Hostname',
  'Hotspot',
  'Hub',
  'Hue - Saturation - Intensity',
  'Hue - Saturation - Lightness',
  'Hue - Saturation - Value',
  'Huffman Coding',
  'Human Interface Device',
  'Human-Computer Interaction',
  'Hungarian Notation',
  'Hybrid Disk Drive',
  'Hybrid Hash Join',
  'Hybrid Merge Join',
  'Hyper-V',
  'Hypercube Architecture',
  'Hyperlink',
  'Hyperspace',
  'Hypertext Markup Language',
  'Hypertext Preprocessor',
  'Hypertext Transfer Protocol',
  'Hypertext Transfer Protocol Secure',
  'Hypothesis',
  'iCloud',
  'Icon',
  'Image Processing',
  'Image Segmentation',
  'Immutable',
  'Imperative Programming',
  'Implementation',
  'Implicit Casting',
  'Implicit Instantiation',
  'Include Directive',
  'Inclusion-Exclusion',
  'Incognito',
  'Inconsistent State',
  'Incremental Development',
  'Independent Component Analysis',
  'Independent Parallelism',
  'Index Entry',
  'Index Operator',
  'Index Record',
  'Index-organized Table',
  'Indexed Nested-loop Join',
  'Indexing String',
  'Indirect Routing',
  'Induction',
  'Infix Notation',
  'Information Gain',
  'Information Overload',
  'Information Retrieval',
  'Information Security',
  'information System',
  'Information Theory',
  'Information-extraction System',
  'Infrastructure',
  'Infrastructure as a Service',
  'Ingres',
  'Inheritance',
  'Initialization',
  'Inline Function',
  'Inner Join',
  'Inner Relation',
  'Inode',
  'Input',
  'Input Device',
  'Insert Into',
  'Insertion',
  'Insertion Operator',
  'Insertion Sort',
  'Instagram',
  'Instance',
  'Instant Messaging',
  'Integer',
  'Integer Factorization',
  'Integer Programming',
  'Integrated',
  'Integrated Circuit',
  'Integrated Development Environment',
  'Integrity',
  'Integrity Constraint',
  'Integrity Manager',
  'Intellectual Property Rights',
  'Intelligent Personal Assistant',
  'Intention-exclusive mode',
  'Intention-shard mode',
  'Inter-Integrated Circuit',
  'Interchange Sort',
  'Interconnection networks',
  'Interface',
  'Interface Description Language',
  'Interfaces',
  'Interference',
  'Interlock',
  'Internal Node',
  'Internet',
  'Internet Address',
  'Internet Control Message Protocol',
  'Internet Engineering Task Force',
  'Internet Exchange Point',
  'Internet Explorer',
  'Internet Group Management Protocol',
  'Internet Information Services',
  'Internet Key Exchange',
  'Internet Mail Access Protocol',
  'Internet Message Access Protocol',
  'Internet of Things',
  'Internet Phone Application',
  'Internet Protocol',
  'Internet Service Provider',
  'Internet Telephony',
  'Interoperation Parallelism',
  'Interpreter',
  'Interpreter Pattern',
  'Interprocess communication',
  'Interquery parallelism',
  'Interrupt',
  'Interrupt Handler',
  'Interrupt Service Routine',
  'Interrupt-request line',
  'Intersect',
  'Intersection set',
  'Intranet',
  'Intraoperation parallelism',
  'Intraquery parallelism',
  'Intro Sort',
  'Intrusion detection systems',
  'Invalidation reports',
  'Invariant',
  'Inverse Document Frequency',
  'Invertible Matrix',
  'Ipconfig',
  'IPsec',
  'Isolated Vertex',
  'Isolation',
  'Isolation Level',
  'isomorphic graphs',
  'Iteration',
  'Iterator',
  'Iterator Pattern',
  'iTunes',
  'Ivy Bridge',
  'Java',
  'Java Applet',
  'Java Data Objects',
  'Java Database Connectivity',
  'Java Development Kit',
  'Java Foundation Classes',
  'Java Runtime Environment',
  'Java Server Pages',
  'Java Virtual Machine',
  'JavaBeans',
  'JavaFX',
  'JavaScript',
  'JavaScript Object Notation',
  'JavaServer Faces Framework',
  'JBoss',
  'John von Neumann',
  'Join Dependency',
  'Joint Picture Experts Group',
  'Joomla',
  'Josephus',
  'Journaling File System',
  'jQuery',
  'JScript .NET',
  'Jukebox System',
  'Jupyter Lab',
  'Just-in-time Compiler',
  'K-means Clustering',
  'k-nearest Neighbors',
  'Kangaroo Code',
  'Keras',
  'Kernel',
  'Kernel Function',
  'Kernel Mode',
  'kernel threads',
  'Key',
  'Key Generation',
  'Key Matrix',
  'Key Pair',
  'Keyboard',
  'Keylogger',
  'Keypad',
  'Keys',
  'Keyword',
  'Kickstarter',
  'Kindle',
  'Kinect',
  'Knapsack Problem',
  "Knight's Tour Problem",
  'Knuth Morris Pratt',
  'Knuth-Morris-Pratt',
  'Kotlin',
  'Kruskal Algorithm',
  'Kubernetes',
  'Label-switched Router',
  'Lambda Expression',
  'Lambda Function',
  'Language Construct',
  'Language-Integrated Query',
  'Laptop',
  'Large-Object Type',
  'Laser Printer',
  'Last In First Out',
  'LaTeX',
  'Layered Architecture',
  'Layout',
  'Lazy Loading',
  'Lazy Propagation',
  'LDAP Data Interchange Format',
  'Leaf',
  'Leaky Bucket Mechanism',
  'Least Recently Used',
  'Least Significant Bit',
  'Least-cost Path',
  'Left Outer Join',
  'Legacy System',
  'Levenshtein Distance',
  'Lexicographical Order',
  'LibreOffice',
  'License Key',
  'Lightweight Directory Access Protocol',
  'Likelihood',
  'Limited-scope Flooding',
  'Line',
  'Linear',
  'Linear Algebra',
  'Linear Equation',
  'Linear Programming',
  'Linear Recursion',
  'Linear Regression',
  'Linear Search',
  'Linear Time',
  'Link',
  'Link state Algorithm',
  'Link-layer Protocol',
  'Link-layer Switch',
  'Link-scheduling Discipline',
  'Link-state Advertisement',
  'Linked List',
  'Linker',
  'Linux Kernel',
  'LISP',
  'Little-endian',
  'Livelock',
  'Local Area Network',
  'Local Features',
  'Local Host',
  'Local Procedure Call',
  'Local Replacement Algorithm',
  'Local Timestamp',
  'Local Variable',
  'Local Wait-for Graph',
  'Localization',
  'Location',
  'Location-dependent Query',
  'Lock Manager',
  'Locking Protocol',
  'Log Disk',
  'Log File',
  'Log Likelihood',
  'Log Record',
  'Log Sequence Number',
  'Log Writer Process',
  'Logarithm Time',
  'Logical Clock',
  'Logical Design',
  'Logical Link Control',
  'Logical Logging',
  'Logical Memory Address',
  'Logical Operation',
  'Logical Operator',
  'Logical Undo Operation',
  'Login',
  'Logistic Regression',
  'Lollipop',
  'Long-duration Transaction',
  'Long-Term Evolution',
  'Longest Common Subsequence',
  'Lookup',
  'Loop',
  'Loop Invariant',
  'Loop Structure',
  'Loss-tolerant',
  'Lossless Compression',
  'Lossless-join Decomposition',
  'Lossy Compression',
  'Lossy Decomposition',
  'Lotus Software',
  'Low Level Virtual Machine',
  'Lspci',
  'LUA',
  'LulzSec',
  'Machine Language',
  'Machine Learning',
  'macOS',
  'Magento',
  'Magic Leap',
  'Magic Number',
  'Magnetic Disk',
  'Magnifier',
  'Mail Access Protocol',
  'Mailbox',
  'Main-memory Database System',
  'Mainboard',
  'Mainframe',
  'Majority Protocol',
  'Malicious Packet Attack',
  'Malware',
  'Man-in-the-middle Attack',
  'Management Information Base',
  'Mandatory Access Control',
  'Manhattan Distance',
  'Manipulator',
  'Mantissa',
  'Many-to-many Mapping',
  'Maple',
  'Mapping cardinalities',
  'MapReduce',
  'Marketplace',
  'Markov Chain',
  'Markov Model',
  'Markov Process',
  'Markup Language',
  'Maskable Interrupts',
  'Mass-storage management',
  'Master Boot Record',
  'Master Key',
  'Master Table',
  'Master-Slave Replication',
  'Material Design',
  'Materialized Query Table',
  'Materialized View',
  'Mathematica',
  'Matlab',
  'Matrix Laboratory',
  'Max Flow Min Cost',
  'Maximum Flow Problem',
  'Maximum Segment Size',
  'Maximum Transmission Unit',
  'Mean Time To Failure',
  'Media',
  'Media Access Control Address',
  'Media Player',
  'Media Transfer Protocol',
  'Mediator Pattern',
  'Mediators',
  'Member Function',
  'Member-wise Copy',
  'Memcached',
  'Memento Pattern',
  'Memoization',
  'Memory',
  'Memory Access',
  'Memory Address',
  'Memory Allocation',
  'Memory Card',
  'Memory Fragment',
  'Memory Leak',
  'Memory Management Unit',
  'Memory Mapping',
  'Memory Stick',
  'Memory Transactions',
  'Memory-address Register',
  'Memory-mapped',
  'Merge Sort',
  'Merge-join',
  'Merge-purge operation',
  'Mesh System',
  'Message Authentication Code',
  'Message Box',
  'Message Broker',
  'Message Delivery Process',
  'Message Digest',
  'Message Digest Algorithm',
  'Metadata',
  'Metaprogramming',
  'Metering Function',
  'Method',
  'Method Overloading',
  'Method Overriding',
  'Metric Space',
  'Metropolitan Area Network',
  'Microcomputer',
  'Microkernel',
  'Microprocessor',
  'Microsoft',
  'Microsoft Active Server Pages',
  'Microsoft Build',
  'Microsoft Cortana',
  'Microsoft Developer Network',
  'Microsoft Foundation Class',
  'Microsoft Office',
  'Microsoft Silverlight',
  'Microsoft SQL Server',
  'Microsoft Surface',
  'Microsoft Transaction Server',
  'Microsoft Visual Studio',
  'Microsoft Windows',
  'Microsoft Word',
  'Minesweeper',
  'Minimum Spanning Tree',
  'Minimum Weighted Vertex Cover',
  'Mo Algorithm',
  'Mobile Application',
  'Mobile Web',
  'Mobile World Congress',
  'Mobius Function',
  'Model View Controller',
  'Model View View Model',
  'Model-View-Control design',
  'Modeling',
  'Modem',
  'Modifier',
  'Modular Data Center',
  'Modular Exponentiation',
  'Modulus Operator',
  'MongoDB',
  'Monitor',
  'Monolithic Kernel',
  'Moodle',
  'Moore Law',
  'Most Recently Used',
  'Most Significant Bit',
  'Most-specific Type',
  'Motherboard',
  'Motorola',
  'Mounting',
  'Mouse',
  'Moving Picture Experts Group',
  'Mozilla Firefox',
  'Mozilla Thunderbird',
  'Multicast',
  'Multicast Routing',
  'Multicast Source Discovery Protocol',
  'Multicasting',
  'Multicore',
  'Multicore Processor',
  'Multidatabase System',
  'Multidimensional Data',
  'Multilevel Feedback-queue',
  'Multilinear Subspace Learning',
  'Multimaster Replication',
  'Multimedia',
  'Multimedia Data',
  'Multiple Inheritance',
  'Multiple Library Linking',
  'Multiple Thread',
  'Multiple-key Access',
  'Multiplexing',
  'Multiplicative Function',
  'Multiprotocol Label Switching',
  'Multiquery Optimization',
  'Multiset',
  'Multiset Relational Algebra',
  'Multisystem applications',
  'Multitasking',
  'Multithreading',
  'Multivalued attributes',
  'Multivalued dependencies',
  'Multiversion concurrency control',
  'Multiway splits',
  'Mutable',
  'Mutex',
  'Mutual Exclusion',
  'Mutual Recursion',
  'Mutual-exclusion condition',
  'MySpace',
  'MySQL',
  'N-way merge',
  'Naive Algorithm',
  'Naive Bayes',
  'Naive Bayesian classifiers',
  'Naive User',
  'Named Entity Recognition',
  'Nameserver',
  'Namespace',
  'Naming Conventions',
  'Nanocomputer',
  'Native Application',
  'Natural Join',
  'Natural Language Processing',
  'Navigate',
  'Near Field Communication',
  'Nearest Neighbor Query',
  'Negative Acknowledgment',
  'Neighbor-to-neighbor Communication',
  'Nested Class',
  'Nested Recursion',
  'Nested Subqueries',
  'Nested-loop Join',
  'NetBeans',
  'Netezza',
  'Netflix',
  'Netscape',
  'Network',
  'Network Access Point',
  'Network Adapter',
  'Network Address Translation',
  'Network Cache Server',
  'Network Edge',
  'Network File System',
  'Network Flow',
  'Network Information Service',
  'Network Interface Card',
  'Network Layer',
  'Network News Transfer Protocol',
  'Network Operations Center',
  'Network Security',
  'Network Time Protocol',
  'Network Topology',
  'Network Virtual Memory',
  'Network-control Protocol',
  'Network-layer Component',
  'Neural Network',
  'New Technology File System',
  'Newline Character',
  'Nintendo Switch',
  'No-force Policy',
  'No-steal Policy',
  'Node',
  'NodeJS',
  'Nonacceptable Termination State',
  'Nonclustering',
  'Nondeclarative Action',
  'Nondeterministic Finite Automaton',
  'Nondeterministic Polynomial',
  'Nonpreemptive Scheduling',
  'Nonrepeatable Read',
  'Nonrepudiation',
  'Nonunique Search Key',
  'Nonvolatile Storage',
  'Nonvolatile Write Buffer',
  'NOR Flash Memory',
  'Normal Distribution',
  'Normal Form',
  'Normalization',
  'NoSQL',
  'Notebook',
  'Notepad++',
  'Notification',
  'NP-Complete',
  'NP-Hard',
  'NSLookup',
  'Null',
  'Null Bitmap',
  'Null Pointer',
  'Null Value',
  'Numeric Operation',
  'Numerical Analysis',
  'Object',
  'Object Database Management Group',
  'Object Recognition',
  'Object-based Database',
  'Object-oriented Data Model',
  'Object-oriented Database',
  'Object-oriented Programming',
  'Object-relational Data Model',
  'Object-relational Mapping',
  'Objective-C',
  'Observable External Write',
  'Observer',
  'Observer Pattern',
  'Octave',
  'One-to-many Mapping',
  'One-to-one Mapping',
  'OneDrive',
  'Online Analytical Processing',
  'Online Transaction Processing',
  'Open Database Connectivity',
  'Open Document Format',
  'Open Shortest Path First',
  'Open Source',
  'Open Statement',
  'Open Systems Interconnection',
  'Open-address Hash Table',
  'Open-source Software',
  'OpenCV',
  'OpenGL',
  'OpenGL Shading Language',
  'OpenOffice',
  'OpenSSL',
  'Opera',
  'Operand',
  'Operating System',
  'Operator',
  'Operator Operand',
  'Operator Overloading',
  'Operator Tree',
  'Optical Character Recognition',
  'Optical Disk',
  'Optical Distribution Network',
  'Optical Fiber',
  'Optical Flow',
  'Optical Mark Reader',
  'Optical Network Terminator',
  'Optical Storage',
  'Optimal',
  'Optimal Binary Search Tree',
  'Optimal Margin Classifier',
  'Optimization',
  'Optimization Problem',
  'Optimizer',
  'Optimus',
  'Oracle',
  'Oracle Enterprise Manager',
  'Oracle Tuxedo',
  'Order By',
  'Order-statistic Tree',
  'Ordered Pair',
  'Organize By Dimension',
  'Out-of-band',
  'Outer Join',
  'Outer Relation',
  'Outliner',
  'Output',
  'Output Buffer',
  'Output Device',
  'Outsourcing',
  'Over The Top',
  'Overfitting',
  'Overflow',
  'Overflow Resolution',
  'Overlapping Entity Set',
  'Overlapping Fragment',
  'Overlapping Specialization',
  'Overlay Network',
  'Overload',
  'Overload Resolution',
  'Overloading',
  'Overriding',
  'Overwatch',
  'Owner Rights',
  'Ownership',
  'Packet',
  'Packet Classification',
  'Packet Satellite',
  'Packet Sniffer',
  'Packet Switching',
  'Packet-radio Network',
  'Padding',
  'Page Allocator',
  'Page Cache',
  'Page Offset',
  'Page Replacement',
  'Page Shipping',
  'Page-buffering Algorithm',
  'Page-directory Entries',
  'Page-fault Rate',
  'Page-replacement Algorithm',
  'PageRank',
  'Pages Per Minute',
  'PageView',
  'Paging',
  'Pair Programming',
  'Palindrome',
  'Panorama',
  'Parallel Binary Search',
  'Parallel Computing',
  'Parallel Database',
  'Parallel External Sort-merge',
  'Parallel Join',
  'Parallel Processing',
  'Parallel System',
  'Parameter',
  'Parameter Style General',
  'Parametric Query Optimization',
  'Parent Class',
  'Parity Bit',
  'Parity Check',
  'Parser',
  'Parsing',
  'Part Of Speech',
  'Participation Constraint',
  'Partition',
  'Partner Interface Processes',
  'Pascal',
  'Pass By Reference',
  'Passive Optical Network',
  'Password',
  'Patch',
  'Path',
  'Path Compression',
  'Path-name Translation',
  'Pattern Matching',
  'Pattern Recognition',
  'Paypal',
  'Peak Rate',
  'Peer',
  'Peer-to-peer',
  'Penetration Testing',
  'Pentium',
  'Per-hop behavior',
  'Perfect Hashing',
  'Performance Benchmark',
  'Performance Management',
  'Performance Tuning',
  'Peripheral Component Interconnect',
  'Peripheral Device',
  'Perl',
  'Permanent Address',
  'Permission',
  'Persistent Data Structure',
  'Persistent Programming',
  'Personal Area Network',
  'Personal Home Page',
  'Personal Identification Number',
  'Petabyte',
  'Phantom Read',
  'Physical',
  'Physical Address',
  'Physical Data Independence',
  'Physical Design',
  'Physical Layer',
  'Physical Memory Address',
  'Physical-design Phase',
  'Physical-layer Protocol',
  'Picture Transfer Protocol',
  'Ping',
  'Pinterest',
  'Pixel',
  'Pixels Per Inch',
  'Plaintext',
  'Planar Graph',
  'Platform',
  'Platform as a Service',
  'Playback Attack',
  'PlayStation',
  'Plug and Play',
  'Pluggable Authentication Module',
  'Plugin',
  'Point-to-Point Protocol',
  'Pointer',
  'Pointer Variable',
  'Points of Presence',
  'Poisoning Attack',
  'Poisson',
  'Polar Coordinates',
  'Policing Disciplines',
  'Policing Mechanisms',
  'Polish Notation',
  'Polish Prefix Notation',
  'Polling',
  'Polyalphabetic Encryption',
  'Polymorphic Type',
  'Polymorphism',
  'Polynomial Code',
  'Polynomial Time',
  'Pooling',
  'Pop',
  'Popularity Ranking',
  'Popup',
  'Port',
  'Portability',
  'Portable Document Format',
  'Portable Executable',
  'Portable Network Graphics',
  'Portable Operating System Interface',
  'Post Office Protocol',
  'Postfix Notation',
  'PostgreSQL',
  'PostScript',
  'Potential Scope',
  'PowerPoint',
  'Pragma',
  'Pre-Master Secret',
  'Precedence',
  'Precedence Graph',
  'Predicates',
  'Prediction',
  'Predictive Analytic',
  'Preemptive Scheduling',
  'Prefix Bit',
  'Prefix Destination Address',
  'Preorder Tree Walk',
  'Prepared Statement',
  'Preprocessing',
  'Preprocessor',
  'Preprocessor Directive',
  'Presentation Facility',
  'Presentation Layer',
  'Prestige Ranking',
  'Pretty Good Privacy',
  'Prim Algorithm',
  'Primary Cache',
  'Primary Copy',
  'Primary Key',
  'Primary Site',
  'Prime Number',
  'Principal Component Analysis',
  'Priority Queue',
  'Privacy',
  'Privacy Policy',
  'Private',
  'Private Branch Exchange',
  'Private Data Member',
  'Private Inheritance',
  'Private Key',
  'Privilege',
  'Probability',
  'Probability Distribution',
  'Procedural Language',
  'Procedural Programming',
  'Procedure',
  'Procedure Lookup Table',
  'Process',
  'Process Control Block',
  'Process Manager',
  'Process Synchronization',
  'Process Termination',
  'Producer-driven Pipeline',
  'Product Owner',
  'Profile',
  'Program Global Area',
  'Programming Interface',
  'Programming Language',
  'Programming Paradigm',
  'Programming Tip',
  'Project Manager',
  'Project-join Normal Form',
  'Projector',
  'Prolog',
  'Properties',
  'Protected',
  'Protocol',
  'Protocol-Independent Multicast',
  'Prototype',
  'Prototype Pattern',
  'Proxy',
  'Proxy Pattern',
  'Proxy Server',
  'Pseudocode',
  'Pseudorandom Number',
  'Pseudotransitivity Rule',
  'Public',
  'Public-key Encryption',
  'Pulling Data',
  'Pulse Code Modulation',
  'Pure Virtual Method',
  'PureView',
  'Purity',
  'Push',
  'Pushdown Automaton',
  'Put Pointer',
  'Python',
  'Pytorch',
  'Quadratic Split',
  'Quadratic Time',
  'Quadtree',
  'Quality Assurance',
  'Quality Control',
  'Quality of Service',
  'Quantization',
  'Quantum Computer',
  'Query',
  'Query Cost',
  'Query Evaluation Engine',
  'Query Language',
  'Query Optimization',
  'Query Optimizer',
  'Query Processing',
  'Query-evaluation Plan',
  'Query-execution Engine',
  'Query-execution Plan',
  'Question Answering',
  'Queue',
  'Queueing System',
  'QuickSort',
  'Quorum Consensus Protocol',
  'R-trees',
  'Race Condition',
  'Radio',
  'Radio Button',
  'Radio Network Controller',
  'Radix Sort',
  'Rainbow Table',
  'Random Access Memory',
  'Random Access Protocol',
  'Random Early Detection Algorithm',
  'Random Forest',
  'Random Sample',
  'Random Walk Model',
  'Range Tree',
  'Range-partitioning Sort',
  'Range-partitioning Vector',
  'Ranking',
  'Rapid Application Development',
  'Raspberry Pi',
  'Raster Data',
  'Raster Graphics',
  'Rational Rose',
  'Rational Unified Process',
  'Raw Data',
  'Read Only',
  'Read Quorum',
  'Read Uncommitted',
  'Read-only Memory',
  'Read-write Contention',
  'Real-time Application',
  'Real-time Embedded System',
  'Real-time Interactive Application',
  'Real-time Transaction System',
  'Really Simple Syndication',
  'Recall',
  'Recommendation System',
  'Recovery Interval',
  'Recovery Time',
  'Rectified Linear Unit',
  'Recurrent Neural Network',
  'Recursion',
  'Recursive Query',
  'Recursive Relationship Set',
  'Recycle Bin',
  'Red-Black Tree',
  'Redis',
  'Redo',
  'Reduced Instruction Set Computing',
  'Redundancy',
  'Redundant Array of Independent Disks',
  'Reference',
  'Reference Parameter',
  'Reference Variable',
  'referencing relation',
  'Referential Integrity',
  'Referral',
  'Reflection',
  'Reflexivity Rule',
  'Refresh Rate',
  'Region Quadtree',
  'Register',
  'Registry',
  'Regression',
  'Regular Expression',
  'Regular Language',
  'Regularization',
  'Reinforcement Learning',
  'Reinterprest Casting',
  'Relation',
  'Relation Instance',
  'Relation Model',
  'Relation Scheme',
  'Relational Algebra',
  'Relational Calculus',
  'Relational Database',
  'Relational Table',
  'Relationship Set',
  'Relative Distinguished Name',
  'Relevance',
  'Relevance feedback',
  'Relocation',
  'Remote Access Control',
  'Remote Access Tool',
  'Remote Backup System',
  'Remote Control',
  'Remote File Access',
  'Remote Procedure Call',
  'Rename Operation',
  'Repeat Loop',
  'Repeatable Read',
  'Replication',
  'Representation',
  'Representational State Transfer',
  'Request for Comments',
  'Request Forgery',
  'Request Operation',
  'Research & Development',
  'Residual Network architecture',
  'Resolution',
  'Resource Acquisition Is Initialization',
  'Resource Description Framework',
  'Resource manager',
  'Response time',
  'Responsive Web',
  'Restriction',
  'ResultSet object',
  'Retrieval',
  'Return',
  'Return Oriented Programming',
  'Reusability',
  'Reverse Engineering',
  'Reverse Path Forwarding',
  'Reverse Polish Notation',
  'Review',
  'Revoke',
  'Rich Site Summary',
  'Rich Text Format',
  'Right Outer Join',
  'Risk Management',
  'Robotics',
  'Role-based Access Control',
  'Roles',
  'Rollback',
  'Rollup',
  'Root Class',
  'Rooted trees',
  'Round Trip Time',
  'Round-robin Queuing',
  'Round-robin Scheduling Algorithm',
  'Round-trip Time',
  'Router',
  'Routing Control Platform',
  'Routing Information Protocol',
  'Row Trigger',
  'Ruby',
  'Ruby on Rails',
  'Runtime Error',
  'Safari',
  'Safe Mode',
  'Satellite links',
  'Savepoints',
  'Scala',
  'Scalable Matrix Extension',
  'Scalable Vector Extension',
  'Scalable Vector Graphics',
  'Scalar subqueries',
  'Scaleup',
  'Scanner',
  'Scheduling',
  'Schema',
  'Schema Definition',
  'Schema Diagrams',
  'Scope',
  'Scoped Enumeration',
  'Scripting Language',
  'Scrolling',
  'Scrum',
  'Scrum Master',
  'Search Algorithm',
  'Search Engine',
  'Search Engine Optimization',
  'Search Engine Spamming',
  'Search Key',
  'Second Normal Form',
  'Sector',
  'Secure Communication',
  'Secure Copy Protocol',
  'Secure Electronic Transaction',
  'Secure Hash Algorithm',
  'Secure Network Programming',
  'Secure Shell',
  'Secure Socket Layer',
  'Security',
  'Security Assertion Markup Language',
  'Security Association Database',
  'Seek times',
  'Segment',
  'Segmentation',
  'Select',
  'Selection Sort',
  'Self-loop',
  'Semantic Web',
  'Semaphore',
  'Semicolon',
  'Semiconductor',
  'Semistructured data model',
  'Sensor',
  'Sentinel',
  'Sequence Association',
  'Sequence Counter',
  'Sequence Diagram',
  'Sequential Access',
  'Sequential File',
  'Sequential Scan',
  'Sequential Search',
  'Sequential-access Storage',
  'Sequentially Access',
  'Serial Advanced Technology Attachment',
  'Serializable',
  'Server',
  'Server Management Studio',
  'Server Programming Interface',
  'Server Side Include',
  'Server-side Scripting',
  'Service Level Agreements',
  'Service Mesh',
  'Session Initiation Protocol',
  'Session Layer',
  'Shadow-copy Scheme',
  'Shadow-paging',
  'Shaker Sort',
  'Shallow Copy',
  'Shared and Intention-exclusive',
  'Shared Scan',
  'Shared-disk Architecture',
  'Shared-memory Architecture',
  'Shared-memory Model',
  'Shared-mode Lock',
  'Shared-nothing Architecture',
  'Shareware Software',
  'Shell',
  'Shell Sort',
  'Shift Cipher',
  'Shim',
  'Shortcut',
  'Shorter Inter-frame Spacing',
  'Shortest Job First',
  'Shortest Path',
  'Shortest Seek Time First',
  'Siamese Network',
  'Sidebar',
  'Sigmoid',
  'Signature',
  'Silverlight',
  'Similarity-based Retrieval',
  'Simple Cycle',
  'Simple Gateway Monitoring Protocol',
  'Simple Graph',
  'Simple Mail Transfer Protocol',
  'Simple Object Access Protocol',
  'Single Linked List',
  'Single Lock Manager',
  'Single Page Application',
  'Single Sign On',
  'Single Thread',
  'Single-server Model',
  'Single-valued Attribute',
  'Singleton Pattern',
  'Singly Connected Graph',
  'Singly Linked List',
  'Siri',
  'Site Reintegration',
  'Skip List',
  'SkyDrive',
  'Skype',
  'Slack',
  'Slide Master',
  'Small Computer System Interconnect',
  'SmallTalk',
  'Smart City',
  'Smart Contract',
  'Smart Home',
  'Smartcar',
  'Smartphone',
  'Smartwatch',
  'Snapdragon',
  'Snapshot Isolation',
  'Snapshot Replication',
  'Social Media',
  'Social Network',
  'Socket',
  'Soft Computing',
  'Softmax',
  'Software',
  'Software Architecture',
  'Software as a Service',
  'Software Defined Networking',
  'Software Development kit',
  'Software Engineering',
  'Software Framework',
  'Software Requirements Specification',
  'Solaris',
  'Solid State Drive',
  'Sort Algorithm',
  'Sorting',
  'Sound Card',
  'Source Code',
  'Source Vertex',
  'Sourceforge',
  'Space Overhead',
  'SpaceX',
  'Spam',
  'Spam Email',
  'Spambot',
  'Spanning Tree',
  'Spanning-tree Broadcast',
  'Spark',
  'Sparse Coding',
  'Spatial Data',
  'Speaker',
  'Specialization',
  'Specialty Database',
  'Specification',
  'Speech Recognition',
  'Spider',
  'Spiral Development',
  'Spiral Model',
  'Spring',
  'Spyware',
  'SQL Injection',
  'SQLite',
  'Square-Root Decomposition',
  'Stack',
  'Stack Memory',
  'Stack Overflow',
  'Stack Unwinding',
  'Stackoverflow',
  'Stackoverflow.com',
  'Stakeholder',
  'Standard Generalized Markup Language',
  'Standard Template Library',
  'Standardized',
  'Starburst',
  'Start-up Cost',
  'Startup',
  'Starvation',
  'State Pattern',
  'State Transition',
  'State Value',
  'Statement',
  'Statement Object',
  'Statement Trigger',
  'Static',
  'Static Array',
  'Static Constructor',
  'Static Huffman Coding',
  'Static Local Variable',
  'Static Member',
  'Static Method',
  'Statistical Analysis System',
  'Statistical Learning',
  'Statistics',
  'Status Bar',
  'Steal Policy',
  'Steam',
  'Steganography',
  'Stereoscopic 3D',
  'Storage',
  'Storage Area Network',
  'Storage Definition Language',
  'Storage Manager',
  'Stored Procedure',
  'Strategy',
  'Strategy Pattern',
  'Stream',
  'Stream Cipher',
  'Stream State',
  'Streaming',
  'Stride',
  'String',
  'String Matching',
  'String Operation',
  'Striping Data',
  'Strongly Connected Component',
  'Structural Pattern',
  'Structure Initialization',
  'Structure of Management Information',
  'Structured Data',
  'Structured Programming',
  'Structured Query Language',
  'Structured Type',
  'Stylesheet',
  'Sub-program',
  'Subclass',
  'Subdomain',
  'Subfolder',
  'Sublime',
  'Sublinear Speedup',
  'Submultiset',
  'Subnet',
  'Subprogram',
  'Subroutines',
  'Subscript',
  'Substring',
  'sudo',
  'Suffix',
  'Suffix Array',
  'Suffix Automaton',
  'Suffix Function',
  'Suffix Tree',
  'Super Key',
  'Superclass',
  'Superclass-Subclass Relationship',
  'Supercomputer',
  'Superkeys',
  'Superuser',
  'Supervised Learning',
  'Support Vector Machine',
  'Swap',
  'Swap Space',
  'Sweep Line',
  'Swift',
  'Switch',
  'Sybase',
  'Symbian',
  'Symbolic Constant',
  'Symmetric Key',
  'Symmetric Multiprocessing',
  'Sync',
  'Syntax',
  'Syntax Error',
  'Syntax Tree',
  'System Architecture',
  'System Boot',
  'System Call',
  'System Catalog',
  'System Change Number',
  'System Disk',
  'System Error',
  'Table',
  'Table Inheritance',
  'Tablespaces',
  'Tablet',
  'Tablet Computer',
  'Tag',
  'Tag Library',
  'Tail Recursion',
  'Tape Storage',
  'Task Flow',
  'Taskbar',
  'Team Foundation',
  'Teamplate Method',
  'Technical Report',
  'Technical Support',
  'Telnet',
  'Template',
  'Template Method Pattern',
  'Temporal Data',
  'Temporal Relation',
  'TensorFlow',
  'Terabyte',
  'Term Frequency',
  'Terminal',
  'Terminate',
  'Termination State',
  'Ternary Content Address Memories',
  'Ternary Search',
  'Terrain',
  'Tertiary Storage',
  'Test Case',
  'Test Plan',
  'Test-driven Development',
  'Text Editor',
  'Text File',
  'The Pirate Bay',
  'Theta Join',
  'Thinkpad',
  'Third Normal Form',
  'Third Party Software',
  "Thomas' write rule",
  'Thrashing',
  'Thread',
  'Three-phase Commit Protocol',
  'Three-tier Architecture',
  'Three-way Handshake',
  'Throughput',
  'Thunk',
  'Time Division Multiplexing',
  'Time Sharing',
  'Time To Live',
  'Times New Roman',
  'Timestamp',
  'Timezone',
  'Token',
  'Token Passing',
  'Tomcat',
  'Toolbox',
  'Top-down Design',
  'top-K Optimization',
  'Top-level Domain',
  'Topographic Information',
  'Topological Sorting',
  'Topology',
  'Torrent',
  'Total Commander',
  'Touchpad',
  'Touchscreen',
  'Track',
  'Trackball',
  'Trading Algorithm',
  'Trail',
  'Trailing Zero',
  'Training Instance',
  'Trampoline',
  'Transaction',
  'Transaction Coordinator',
  'Transaction Isolation',
  'Transaction Processing Monitor',
  'Transaction Server System',
  'Transactional Replication',
  'Transactions Consistent Snapshot',
  'Transactions per Second',
  'Transfer of Control',
  'Transfer of Prestige',
  'Transformations',
  'Transistor',
  'Transition Table',
  'Transitive Closure',
  'Transitivity Rule',
  'Translation Lookaside Buffer',
  'Transmission Control Protocol',
  'Transparent Data Encryption',
  'Transport',
  'Transport Layer',
  'Transport Layer Security',
  'Trap',
  'Traveling Salesman Problem',
  'Tree',
  'Trie',
  'Trigger',
  'Trivial File Transfer Protocol',
  'Trojan',
  'Trojan Horse',
  'True Negative',
  'True Predicate',
  'True Relation',
  'Trusted Platform Module',
  'Try Catch',
  'Tumblr',
  'Tuning Hyperparameter',
  'Tuple',
  'Tuple Relational Calculus',
  'Turing Award',
  'Turing Machine',
  'Turing Test',
  'Turnaround Time',
  'Tweet',
  'Twisted Pair Copper Wire',
  'Twitter',
  'Two-factor Authentication',
  'Two-phase Commit Protocol',
  'Two-tier Architecture',
  'Typedef',
  'Typename',
  'Ubuntu',
  'Udemy',
  'Ultrium format',
  'Uncaught Exceptions',
  'Underline',
  'Undo Pass',
  'Unicast',
  'Unicode',
  'Unicode Transformation Format',
  'Unified Extensible Firmware Interface',
  'Unified Modeling Language',
  'Uniform Distribution',
  'Uniform Memory Access',
  'Uniform Resource Identifier',
  'Uniform Resource Locator',
  'Uniform Resource Name',
  'Unikey',
  'Union',
  'Union Compatibility',
  'Union Rule',
  'Unique Key',
  'Uniquifier',
  'Unit of Work',
  'Unity',
  'Universal Coordinated Time',
  'Universal Description, Discovery, and Integration',
  'Universal Mobile Telecommunications Service',
  'Universal Module Definition',
  'Universal Resource Locator',
  'Universal Serial Bus',
  'Universal Turing Machine',
  'Universally Unique Identifier',
  'Unix',
  'Unmatched Vertex',
  'Unordered Associative Container',
  'Unreal Engine',
  'Unshielded Twisted Pair',
  'Unsupervised',
  'Unsupervised Learning',
  'Upcasting',
  'Updatable Result Set',
  'Update',
  'Update-anywhere Replication',
  'Upper Case',
  'Uppercase Manipulator',
  'User Datagram Protocol',
  'User Experience',
  'User Interface',
  'User Mobility',
  'User Requirements',
  'User Story',
  'User-defined Entity Set',
  'User-defined Function',
  'Username',
  'Utilization',
  'Valid Time',
  'Validation',
  'Vanishing gradient',
  'Varchar',
  'Variable',
  'Variable Declaration',
  'VBScript',
  'Vector Container',
  'Vector Data',
  'Vector Space Model',
  'Venn Diagram',
  'Versatility',
  'Version-numbering Schemas',
  'Version-vector Scheme',
  'Vertex',
  'Vertical Fragmentation',
  'Viber',
  'Video Card',
  'Video Graphics Array',
  'Video Server',
  'View',
  'View Definition Language',
  'view Maintenance',
  'View-Master',
  'Viewable Area',
  'Vim',
  'Virtual Address',
  'Virtual Destructor',
  'virtual File System',
  'Virtual Inheritance',
  'Virtual Local Area Network',
  'Virtual Machines',
  'Virtual Memory',
  'Virtual Method',
  'Virtual Private Network',
  'Virtual Private Server',
  'Virtual Processor',
  'Virtual Reality',
  'Virtual Reality Modeling Language',
  'Virtual Table',
  'VirtualBox',
  'Visitor Pattern',
  'Visual Basic',
  'Visual Basic .NET',
  'Visualization',
  'VisualWeb',
  'Viterbi Algorithm',
  'VMWare',
  'Voice over Internet Protocol',
  'Voice Recognition',
  'Void',
  'Volatile Storage',
  'Vsphere',
  'Vulnerability',
  'Wait-for Graph',
  'Walk',
  'Wallet',
  'Waterfall Model',
  'Weak Entity',
  'Wearable Device',
  'Web',
  'Web Application',
  'Web Browser',
  'Web Config',
  'Web Crawler',
  'Web Graphics Library',
  'Web Ontology Language',
  'Web Server',
  'Web Service',
  'Web Services Description Language',
  'Webcam',
  'Webhost',
  'WebLogic',
  'WebObjects',
  'Website',
  'WebSphere',
  'Weight',
  'Weighted Bipartite',
  'Weighted Fair Queuing',
  'Weighted-union Heuristic',
  'What You See is What You Get',
  'WhatsApp',
  'Whois',
  'Wide Area Network',
  'Wide Character',
  'Widget',
  'Wikileaks',
  'Wikipedia',
  'Windows',
  'Windows 7',
  'Windows 8',
  'Windows Azure',
  'Windows Phone',
  'Windows Presentation Foundation',
  'Windows Server',
  'Windows XP',
  'Wired Equivalent Privacy',
  'Wireless Access Point',
  'Wireless Application Protocol',
  'Wireless Communications',
  'Wireless Local Area Network',
  'Wireless Mouse',
  'Wireless Network',
  'Wireless Personal Area Network',
  'Wireless Router',
  'Wireshark Labs',
  'Word Processing',
  'WordArt',
  'WordNet',
  'Wordpress',
  'Workflow',
  'Workload Compression',
  'Worksheet',
  'Workstation',
  'World Wide Web',
  'Worm',
  'Worst case Complexity',
  'Wrapping',
  'Write Once, Read Many',
  'Write Quorum',
  'Write-ahead Logging',
  'Write-write Contention',
  'Xbox',
  'Xbox 360',
  'Xbox One',
  'XCode',
  'XPath',
  'XQuery',
  'Yahoo',
  'Yahoo Messenger',
  'Youtube',
  'Zend Framework',
  'Zero-day Attack',
  'Zero-padding',
  'ZooKeeper'
];
